version: 0.0
os: linux
files:
  - source: target/appstore-service.war.original
    destination: /home/ec2-user/javaapp
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
