#!/bin/bash
##
##install on EC2 instance in AWS
##
cd /home/ec2-user/javaapp
wget https://s3.amazonaws.com/dhqs-mirror-iad/apache-tomcat-8.0.39.tar.gz
mkdir /opt/tomcat
tar xvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
cd /opt/tomcat
sed -i 's|port="8080"|port="80"|g' conf/server.xml
#remove stuff from previous used CodePipeline (should be removed after running once!)
rm -rf webapps/ROOT
rm -rf webapps/spring-boot-service
mv /home/ec2-user/javaapp/spring-boot-service.war webapps/
